### ISSUE TITLE
plantage aprés 5 minutes d'execution

### ISSUE THREAD

**Issue by RomainTourte** [jancelin/RTKlibDroid#3]
Soo many 

socket timeout!
connection ON
socket timeout!
connection ON
socket timeout!
connection ON
socket timeout!
connection ON
socket timeout!
connection ON... 

With some error like :

Unhandled rejection Error: Cannot connect
    at Socket.socket.setTimeout (/Users/Romain/Code/RTKlibDroid/nodejs/read_status_reveiver/node_modules/telnet-client/lib/index.js:85:25)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at Socket._onTimeout (net.js:440:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

OR 

Unhandled rejection Error: Socket closes
    at Socket.socket.on (/Users/Romain/Code/RTKlibDroid/nodejs/read_status_reveiver/node_modules/telnet-client/lib/index.js:121:18)
    at Socket.emit (events.js:189:13)
    at TCP._handle.close (net.js:597:12)

<--- Last few GCs --->

[78994:0x104800000]   660933 ms: Mark-sweep 1397.6 (1425.1) -> 1397.1 (1425.1) MB, 259.7 / 0.0 ms  (average mu = 0.145, current mu = 0.008) allocation failure scavenge might not succeed
[78994:0x104800000]   661165 ms: Mark-sweep 1397.8 (1425.1) -> 1397.4 (1425.6) MB, 229.2 / 0.0 ms  (average mu = 0.082, current mu = 0.009) allocation failure scavenge might not succeed

<--- JS stacktrace --->
==== JS stack trace =========================================
Security context: 0x3bb0e579e6e9 <JSObject>
    0: builtin exit frame: stringify(this=0x3bb0e5791a21 <Object map = 0x3bb05c1042a9>,0x3bb0ea6826f1 <undefined>,0x3bb0ea6826f1 <undefined>,0x3bb03c348579 <JSArray[2]>,0x3bb0e5791a21 <Object map = 0x3bb05c1042a9>)

    1: arguments adaptor frame: 1->3
    2: tryStringify [0x3bb01cacfc39] [/Users/Romain/Code/RTKlibDroid/nodejs/read_status_reveiver/node_modules/socket.io-parser/index.js:~182] [pc...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10003c597 node::Abort() [/usr/local/bin/node]
 2: 0x10003c7a1 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x1001ad575 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x100579242 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 5: 0x10057bd15 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/local/bin/node]
 6: 0x100577bbf v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 7: 0x100575d94 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0x10058262c v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 9: 0x1005826af v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
10: 0x100554534 v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
11: 0x10086c32b v8::internal::IncrementalStringBuilder::Extend() [/usr/local/bin/node]
12: 0x10065486b v8::internal::JsonStringifier::SerializeString(v8::internal::Handle<v8::internal::String>) [/usr/local/bin/node]
13: 0x100657db8 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
14: 0x100655607 v8::internal::JsonStringifier::SerializeJSReceiverSlow(v8::internal::Handle<v8::internal::JSReceiver>) [/usr/local/bin/node]
15: 0x100656058 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
16: 0x1006552ba v8::internal::JsonStringifier::SerializeArrayLikeSlow(v8::internal::Handle<v8::internal::JSReceiver>, unsigned int, unsigned int) [/usr/local/bin/node]
17: 0x100656d60 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
18: 0x100652aef v8::internal::JsonStringifier::Stringify(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
19: 0x10026c7c6 v8::internal::Builtin_Impl_JsonStringify(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
20: 0x255f144dbf9d 
21: 0x255f1448a5c3

**Comment by RomainTourte** [comment]
17h20... Test to solve with command : 
node --max-old-space-size=4096 node_modules/telnet-client/
17h25 .... Still ok receiving telnet info...
17h27 ... some error message
17h30 ... BLAM KO !
